name: Bug Report
description: Report a bug or unexpected behavior in agpod
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Important Notice
        
        **This repository is maintained by GitHub Copilot Agent.** Please do not approach the repository owner for coding tasks or implementation details. All code-related work is handled by automated agents.
        
        Thank you for taking the time to report a bug!
        
        ---
        
        ### 💝 Support This Project
        
        This project uses AI coding agents which incur operational costs. If you find agpod useful, please consider supporting its development:
        
        - ⭐ Star this repository
        - ☕ [Support via GitHub Sponsors](https://github.com/sponsors/towry) (if available)
        - 🐦 Share agpod with others who might find it useful
        
        Your support helps keep this project maintained and improved!
        
  - type: textarea
    id: description
    attributes:
      label: Detailed Issue Description
      description: Provide a clear and detailed description of the bug
      placeholder: |
        What happened? What did you expect to happen?
        Please be as detailed as possible to help us understand the issue.
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With input '...'
        3. See error '...'
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: agpod Version
      description: What version of agpod are you using?
      placeholder: "e.g., 0.3.0 or output from 'agpod --version'"
    validations:
      required: true
      
  - type: dropdown
    id: platform
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS (Apple Silicon M1/M2/M3)
        - macOS (Intel)
        - Linux
        - Windows
        - Other
    validations:
      required: true
      
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of your operating system?
      placeholder: "e.g., macOS 14.5, Ubuntu 22.04, Windows 11"
    validations:
      required: true
      
  - type: input
    id: rust-version
    attributes:
      label: Rust Version (if building from source)
      description: What version of Rust are you using? (if applicable)
      placeholder: "e.g., rustc 1.89.0 or N/A"
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
      placeholder: |
        - Error messages
        - Log output
        - Screenshots
        - Related issues
    validations:
      required: false
