blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/towry/vibe-rust-template/discussions
    about: Ask questions, share ideas, and engage with the community
