name: Feature Request
description: Suggest a new feature or enhancement for agpod
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Important Notice
        
        **This repository is maintained by GitHub Copilot Agent.** Please do not approach the repository owner for coding tasks or implementation details. All code-related work is handled by automated agents.
        
        Thank you for suggesting a new feature!
        
        ---
        
        ### 💝 Support This Project
        
        This project uses AI coding agents which incur operational costs. If you find agpod useful, please consider supporting its development:
        
        - ⭐ Star this repository
        - ☕ [Support via GitHub Sponsors](https://github.com/sponsors/towry) (if available)
        - 🐦 Share agpod with others who might find it useful
        
        Your support helps keep this project maintained and improved!
        
  - type: textarea
    id: description
    attributes:
      label: Detailed Feature Description
      description: Provide a clear and detailed description of the feature you'd like to see
      placeholder: |
        What feature would you like to add or improve?
        Why is this feature important?
        What problem does it solve?
    validations:
      required: true
      
  - type: textarea
    id: implementation
    attributes:
      label: How Do You Want It Implemented?
      description: Describe how you envision this feature working
      placeholder: |
        - How should the feature work?
        - What should the user interface look like (CLI arguments, flags, etc.)?
        - What should the output be?
        - Are there any specific technical approaches you'd prefer?
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case / User Story
      description: Describe the scenario where this feature would be useful
      placeholder: |
        As a [type of user], I want to [do something], so that [I can achieve some goal].
        
        Example workflow:
        1. User does X
        2. Feature does Y
        3. Result is Z
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        - What other approaches could solve this problem?
        - Are there any existing tools or methods you're currently using as a workaround?
    validations:
      required: false
      
  - type: dropdown
    id: platform
    attributes:
      label: Target Platform
      description: Which platform(s) should this feature support?
      multiple: true
      options:
        - All platforms
        - macOS (Apple Silicon M1/M2/M3)
        - macOS (Intel)
        - Linux
        - Windows
    validations:
      required: true
      
  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes to existing functionality?
      options:
        - label: This feature would require breaking changes
          required: false
        - label: This feature is backward compatible
          required: false
          
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here
      placeholder: |
        - Example code snippets
        - Screenshots or mockups
        - Links to similar features in other tools
        - Performance considerations
    validations:
      required: false
