name: Refactor Request
description: Propose code refactoring or improvement without changing functionality
title: "[Refactor]: "
labels: ["refactor"]
body:
  - type: markdown
    attributes:
      value: |
        ## Important Notice
        
        **This repository is maintained by GitHub Copilot Agent.** Please do not approach the repository owner for coding tasks or implementation details. All code-related work is handled by automated agents.
        
        Thank you for proposing a refactoring improvement!
        
        ---
        
        ### 💝 Support This Project
        
        This project uses AI coding agents which incur operational costs. If you find agpod useful, please consider supporting its development:
        
        - ⭐ Star this repository
        - ☕ [Support via GitHub Sponsors](https://github.com/sponsors/towry) (if available)
        - 🐦 Share agpod with others who might find it useful
        
        Your support helps keep this project maintained and improved!
        
  - type: textarea
    id: description
    attributes:
      label: Refactoring Description
      description: Describe what code needs to be refactored and why
      placeholder: |
        What code or module needs refactoring?
        Why is this refactoring necessary?
        What problems does the current implementation have?
    validations:
      required: true
      
  - type: textarea
    id: current-implementation
    attributes:
      label: Current Implementation
      description: Describe the current code structure or approach
      placeholder: |
        - What is the current implementation?
        - What files or modules are affected?
        - What are the pain points?
    validations:
      required: true
      
  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: Describe the refactoring you'd like to see
      placeholder: |
        - How should the code be restructured?
        - What patterns or approaches should be used?
        - What are the expected benefits?
    validations:
      required: true
      
  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What improvements will this refactoring bring?
      placeholder: |
        - Improved code readability
        - Better performance
        - Easier maintenance
        - Better testability
        - Reduced complexity
    validations:
      required: true
      
  - type: checkboxes
    id: scope
    attributes:
      label: Scope of Changes
      description: What areas will be affected?
      options:
        - label: Core functionality
          required: false
        - label: Tests
          required: false
        - label: Documentation
          required: false
        - label: Dependencies
          required: false
        - label: Build system
          required: false
          
  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Will this refactoring require breaking changes?
      options:
        - label: This refactoring would require breaking changes
          required: false
        - label: This refactoring maintains backward compatibility
          required: false
          
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the refactoring here
      placeholder: |
        - Code examples
        - Related issues or PRs
        - Performance benchmarks
        - Technical considerations
    validations:
      required: false
