name: 'Build Rust Binary'
description: 'Build and package Rust binary for a specific target'

inputs:
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-gnu)'
    required: true
  toolchain:
    description: 'Rust toolchain version'
    required: false
    default: 'stable'
  bin_name:
    description: 'Binary name (must match Cargo.toml package name)'
    required: true
  version:
    description: 'Version string for artifact naming'
    required: true

outputs:
  asset_path:
    description: 'Path to the packaged tarball'
    value: ${{ steps.package.outputs.asset_path }}
  asset_name:
    description: 'Name of the packaged tarball'
    value: ${{ steps.package.outputs.asset_name }}

runs:
  using: "composite"
  steps:
    - name: Disable man-db triggers (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db

    - name: Install deps (Linux)
      if: runner.os == 'Linux'
      uses: awalsh128/cache-apt-pkgs-action@v1.5.3
      with:
        packages: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libgtk-3-dev
        version: 1.0

    - name: Install toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        target: ${{ inputs.target }}

    - name: Cache cargo artifacts
      uses: Swatinem/rust-cache@v2

    - name: Build
      shell: bash
      run: cargo build --release --target ${{ inputs.target }} --verbose

    - name: Package
      id: package
      shell: bash
      run: |
        version="${{ inputs.version }}"
        version="${version#v}" # strip leading v if present
        staging="${{ inputs.bin_name }}-${version}-${{ inputs.target }}"
        mkdir -p "$staging"
        cp README.md "$staging/"
        cp target/${{ inputs.target }}/release/${{ inputs.bin_name }} "$staging/${{ inputs.bin_name }}"
        tar czf "$staging.tar.gz" "$staging"
        echo "asset_path=$staging.tar.gz" >> $GITHUB_OUTPUT
        echo "asset_name=$staging.tar.gz" >> $GITHUB_OUTPUT
