name: build-artifacts

on:
  workflow_call:
    inputs:
      tag_name:
        description: "Tag name (e.g. v1.2.3)"
        required: true
        type: string
      upload_url:
        description: "GitHub release upload_url"
        required: true
        type: string
      bin_name:
        description: "Binary name"
        required: false
        default: template
        type: string
  release:
    types: [created]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Upload Binaries
    runs-on: ${{ matrix.os }}
    env:
      BIN_NAME: ${{ inputs.bin_name || 'vibe-rust-template' }}
      VERSION: ${{ inputs.tag_name || github.event.release.tag_name }}
      UPLOAD_URL: ${{ inputs.upload_url || github.event.release.upload_url }}
    strategy:
      matrix:
        build: [linux, macos-arm]
        include:
          - build: linux
            os: ubuntu-20.04
            rust: stable
            target: x86_64-unknown-linux-gnu
          - build: macos-arm
            os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libgtk-3-dev

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --verbose

      - name: Package
        shell: bash
        run: |
          version="${VERSION#v}" # strip leading v
          staging="${BIN_NAME}-${version}-${{ matrix.target }}"
          mkdir -p "$staging"
          cp README.md "$staging/"
          cp target/${{ matrix.target }}/release/${BIN_NAME} "$staging/"
          tar czf "$staging.tar.gz" "$staging"
          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/octet-stream
